app/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout
#from loginapp.views import (login_view, register_user, logout_view)

urlpatterns = [
    url(r'^$', views.index),
    url(r'^data$', views.data),
    url(r'^myview$', views.my_view),
    url(r'^registration$', views.register_user, name = "registration"),
    url(r'^profile$', views.profile, name='profile'),
    #url(r'^accounts/login/$', auth_views.login, {'template_name': 'index.html','authentication_form': LoginForm}, name="login") ,
	url(r'^logout$', views.logout_view, name='logout'),
    url(r'^login/', views.login_view, name = "login_view"),
    url(r'^accesstoken$', views.accesstoken),
    #url(r'^success$', views.success),
]

fbsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app import views
from fitapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls')),
    url(r'^fitbit/', include('fitapp.urls')),
]

app/forms.py
# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('username', 'password', 'email')

# class ProfileForm(forms.ModelForm):
#     class Meta:
#         model = Profile
#         fields = ('firstname', 'lastname', 'fitbitid')

from django import forms            
from django.contrib.auth.models import User   # fill in custom user info then save it 
from django.contrib.auth.forms import UserCreationForm      

class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True)
    firstname = forms.CharField(required = True)
    lastname = forms.CharField(required = True)

    class Meta:
        model = User
        fields = ('username','email', 'password1', 'password2')

    def clean(self):
        cleaned_data = super(MyRegistrationForm, self).clean()
        temp_password = cleaned_data['password1']
        if "password" in temp_password:
            self.add_error('password1', 'Your password is too simple.')

        return cleaned_data

    def save(self,commit = True):   
        user = super(MyRegistrationForm, self).save(commit = False)
        #user_profile = UserProfile(user=user, email = self.cleaned_data['email'], firstname = self.cleaned_data['firstname'],
        #lastname = self.cleaned_data['lastname'], fitbitid = self.cleaned_data['fitbitid'])
        user.email = self.cleaned_data['email']
        user.firstname = self.cleaned_data['firstname']
        user.lastname = self.cleaned_data['lastname']

        if commit:
            user.save()

        return user

app/templates/connectsuccess.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Action</title>
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% load staticfiles %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet" />

    </head>

<body>
<br />
    <center><a>{{showtext}}</a></center><br />
    <center><a  href = {{href}}><button type="button">{{buttontext}}</button></a></center>

</body>

app/templates/index.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Sign-Up/Login Form</title>
  <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

  {% load staticfiles %}
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
      <!-- <link rel="stylesheet" href="css/style.css"> -->
</head>

<body>
  <div class="form">
      <ul class="tab-group">
        <li id="signUpTab" class="tab active"><a href="#signup">Sign Up</a></li>
        <li id="loginTab" class="tab"><a href="#login">Log In</a></li>
      </ul>
      
      <div class="tab-content">
        <div id="signup">   
          <h1>Health Metrics Registration</h1>
          {% if form.errors %}
              {% for field in form %}
                  {% for error in field.errors %}
                      <div id ="errors">
                          <center><strong><span class="glyphicon glyphicon-warning-sign"></span></span> {{ error|escape }}</strong></center>
                      </div>
                  {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                  <div id="non-field-errors">
                      <center><strong>{{ error|escape }}</strong></center>
                  </div>
              {% endfor %}
          {% endif %}
          
          <form  action="{% url 'registration' %}" method="post">
          {% csrf_token %}
          <!-- {{ MyRegistrationForm.as_p }} -->
          <div class="top-row">
            <div class="field-wrap">
              <label>
                First Name<span class="req">*</span>
              </label>
              <!-- <input type="text" required autocomplete="off" /> -->
              <input id="id_firstname" name="firstname" type="text" required="">
            </div>
        
            <div class="field-wrap">
              <label>
                Last Name<span class="req">*</span>
              </label>
             <!--  <input type="text"required autocomplete="off"/> -->
              <input id="id_lastname" name="lastname" type="text" required="">
            </div>
          </div>

          <div class="field-wrap">
            <label>
              Email Address<span class="req">*</span>
            </label>
            <input id = "id_email" name="email" type="email" required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              User Name <span class="req">*</span>
            </label>
            <input id = "id_username" name="username" type="text" required autocomplete="off"/>
          </div>

          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <!-- <input type="password"required autocomplete="off"/> -->
            <input id="id_password" name="password1" type="password" required="">
          </div>

          <div class="field-wrap">
            <label>
              Set A Password<span class="req">*</span>
            </label>
            <!-- <input type="password"required autocomplete="off"/> -->
            <input id="id_password" name="password2" type="password" required="">
          </div>
          
          <button type="submit" class="button button-block"/>Get Started</button>
          
          </form>
          <!-- The Modal -->
          <div id="modal" class="modal" submitted="{{success}}">
            <!-- Modal content -->
            <div class="modal-content">
              <div class="modal-body">
                <p>Thank you, you are registered!</p>
                <button id="modalButton" class="modalButton" type="button"/>Continue</button>
              </div>
            </div>

          </div>

        </div>
        
        <div id="login">   
          <h1>Welcome Back!</h1>
          
          <form  action="{% url 'login_view' %}" method="post">
            {% csrf_token %}
            <div class="field-wrap">
            <label>
              User Name<span class="req">*</span>
            </label>
            <input id = "id_username" name="username" type="text" required autocomplete="off"/>
          </div>
          
          <div class="field-wrap">
            <label>
              Password<span class="req">*</span>
            </label>
            <input id = "id_password" name="password" type="password"required autocomplete="off"/>
          </div>
          
          <p class="forgot"><a href="#">Forgot Password?</a></p>
          
          <button class="button button-block"/>Log In</button>
          
          </form>

        </div>
        
      </div><!-- tab-content -->
      
</div> <!-- /form -->

  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

  <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

app/templates/profile.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
    <link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    {% load staticfiles %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet" />
      <!-- <link rel="stylesheet" href="css/style.css"> -->

</head>

<body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Health Metrics</a>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="#">About us</a></li>
          <li><a href="#">My data</a></li>
        </ul>
          <ul class="nav navbar-nav navbar-right">
          <li><a href="logout"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        </ul>
      </div>
    </nav>
    <div id = "core-body">
        <div id = "left-half">
            <center><h2>{{username}}</h2></center>
            <div id="left-half-profile-image">
                <img src="{% static 'images/black-profile.png' %}" style="width:100%;">
            </div>
            <br>
            <center><h3>User Information</h3></center>
            <center><p>some information</p></center>
            <center><p>some information</p></center>
            <center><p>some information</p></center>
            <center><p>some information</p></center>
            <center><p>some information</p></center>
            <center><p>some information</p></center>

            <center><a  href = /app ><button type="button">Fitbit Connect</button></a></center>
        </div>

        <div id = "right-half">
            <div id = "top-right-half">
                <center><h2>Current Data</h2></center>
            </div>
            <div id = "bot-right-half">
                <center><h2>Last Week's Data</h2></center>
            </div>
        </div>
    </div>
</body>